language: python
python:
  - "2.7"

branches:
  only:
  - master
  - dev
  - merge

env:
  - PYTHONPATH=.

install:
  - "wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-1.7.3.tar.gz"
  - "tar -xzf elasticsearch-1.7.3.tar.gz"
  - "sudo cp -f tests/travis/elasticsearch.yml /etc/elasticsearch/elasticsearch.yml"
  - "./elasticsearch-1.7.3/bin/elasticsearch &"
  - "pip install -r requirements.txt"
  - "wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200"

# command to run tests
script:
  - tests/travis/run.sh
