language: python
python:
  - "2.7"

install: "pip install -r requirements.txt"

env:
  - PYTHONPATH=.

services:
  - elasticsearch


# command to run tests
script: tests/scripts/run.sh


addons:
  apt:
    sources:
      - elasticsearch-1.7
    packages:
      - elasticsearch

