language: python
python:
  - "2.7"

install: "pip install -r requirements.txt"

env:
  - PYTHONPATH=.


before_install:
  - whereis elasticsearch

before_script:
  - "elasticsearch -v"
  - "curl http://localhost:9200/"


# command to run tests
script: tests/scripts/run.sh

services:
  - elasticsearch

addons:
  apt:
    sources:
      - elasticsearch-1.7
    packages:
      - elasticsearch

