# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

jobs:
  test:
    docker:
      - image: circleci/python:2.7.15

      # ELASTICSEARCH
      # https://www.elastic.co/guide/en/elasticsearch/reference/6.3/docker.html
      - image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
        environment:
          cluster.name: activedata-test
          bootstrap.memory_lock: true
          ES_JAVA_OPTS: "-Xms512m -Xmx512m"
          bootstrap.system_call_filter: false
          transport.host: localhost
          discovery.type: single-node

    working_directory: ~/repo

    environment:
      PYTHONPATH: .:vendor

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            pip install virtualenv
            python -m virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          environment:
            PYTHONPATH: .:vendor
            TEST_CONFIG: tests/travis/app.json
          command: |
            . venv/bin/activate
            python active_data/app.py --settings=tests/travis/app.json &
            sleep 5
            python -m unittest discover tests --failfast

      - store_artifacts:
          path: test-reports
          destination: test-reports

  dock:
    working_directory: ~/repo

    docker:
      - image: docker:18.06-git

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            echo BUILDING ACTIVEDATA WITH TAG = $REPO_TAG
            docker build --file resources/docker/activedata.dockerfile --build-arg REPO_TAG=${CIRCLE_TAG} --no-cache --tag activedata .
      - run:
          name: Save Docker image layer cache
          command: |
            docker save -o /tmp/activedata.tar activedata

      - store_artifacts:
          path: /tmp/activedata.tar

workflows:
  version: 2
  test_and_dockerize:
    jobs:
      - test:
          filters:
            branches:
              only:
                - bugzilla-etl
      - dock:
          requires:
            - test
          filters:
            tags:
              only: /^v2\..*/
